<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.26100.0</TargetPlatformMinVersion>
    <SupportedOSPlatformVersion>10.0.26100.0</SupportedOSPlatformVersion>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x64</Platforms>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <UseWinUI>true</UseWinUI>
    <WindowsPackageType>None</WindowsPackageType>
    <LangVersion>preview</LangVersion>
    <Nullable>enable</Nullable>
    <SelfContained>true</SelfContained>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ImplicitUsings>enable</ImplicitUsings>
    <IncludeReferencedProjectsInXamlTypeResolution>false</IncludeReferencedProjectsInXamlTypeResolution>
  </PropertyGroup>

  <PropertyGroup>
    <Product>ClipboardZenHanConverter</Product>
    <Version>0.0.1</Version>
    <Description>A utility application that automatically converts text in the clipboard, such as converting full-width to half-width characters.</Description>
    <RootNamespace>ClipboardZenHanConverter</RootNamespace>
    <AssemblyName>ClipboardZenHanConverter</AssemblyName>
    <PackageTags>clipboard; zen; han; convert</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\core\core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="CommunityToolkit.WinUI.Controls.Primitives" Version="8.2.251219" />
    <PackageReference Include="CommunityToolkit.WinUI.Controls.Segmented" Version="8.2.251219" />
    <PackageReference Include="CommunityToolkit.WinUI.Controls.SettingsControls" Version="8.2.251219" />
    <PackageReference Include="CommunityToolkit.WinUI.UI.Controls.DataGrid" Version="7.1.2" />
    <PackageReference Include="EsUtil.Helper.ZenHanConverter" Version="0.0.3" />
    <PackageReference Include="EsUtil.WinUI3.Controls.MultiColumnPanel" Version="1.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.2270" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.2.0" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.WinUI.Managed" Version="3.0.1" />
  </ItemGroup>

</Project>
