<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>ClipboardZenHanConverter.Core</RootNamespace>
    <AssemblyName>ClipboardZenHanConverter.Core</AssemblyName>
    <Description>Core logic and models for ClipboardZenHanConverter</Description>
    <Version>0.0.1</Version>
    <Copyright>Copyright (c) 2025</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="EsUtil.Helper.ZenHanConverter" Version="0.0.3" />
  </ItemGroup>

</Project>
